spring.application.name=database_module

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hybernate.ddl-auto=update


